In [2]:
import sys
sys.path.append( '..' )

import pandas as pd
import pandas_profiling as pp

In [3]:
pip install Matplotlib

Requirement already satisfied: Matplotlib in c:\users\allan\miniconda3\lib\site-packages (3.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\allan\miniconda3\lib\site-packages (from Matplotlib) (21.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\allan\miniconda3\lib\site-packages (from Matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\allan\miniconda3\lib\site-packages (from Matplotlib) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\allan\miniconda3\lib\site-packages (from Matplotlib) (8.4.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\allan\miniconda3\lib\site-packages (from Matplotlib) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\allan\miniconda3\lib\site-packages (from Matplotlib) (2.4.7)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\allan\miniconda3\lib\site-packages (from Matplotlib) (4.29.1)
Requirement already satisfied: numpy>=1.17 in c:\users\allan\miniconda3\lib\site-packages (from Matplotlib) (1.21.2)
Requirement already satisfied: six>=1.5 in c:\users\allan\miniconda3\lib\site-packages (from python-dateutil>=2.7->Matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
ufc_table = pd.read_csv('../data/ufc.csv')

In [5]:
ufc_table.head()

,BPrev,BStreak,B_Age,B_Height,B_HomeTown,B_ID,B_Location,B_Name,B_Weight,B__Round1_Grappling_Reversals_Landed,...,R__Round5_TIP_Ground Time,R__Round5_TIP_Guard Control Time,R__Round5_TIP_Half Guard Control Time,R__Round5_TIP_Misc. Ground Control Time,R__Round5_TIP_Mount Control Time,R__Round5_TIP_Neutral Time,R__Round5_TIP_Side Control Time,R__Round5_TIP_Standing Time,winby,winner
0,0,0,38.0,193.0,Hounslow England,808,Amsterdam The Netherlands,Alistair Overeem,120.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DEC,blue
1,0,0,36.0,172.0,"Chicago, Illinois United States",1054,"Chicago, Illinois United States",Ricardo Lamas,65.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DEC,red
2,0,0,39.0,167.0,"Isla Vista , California USA",959,"Sacramento, California USA",Urijah Faber,61.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KO/TKO,red
3,0,0,33.0,167.0,"San Diego, CA USA",1056,"San Diego, CA USA",Danny Martinez,56.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DEC,red
4,0,0,36.0,185.0,Southampton England,2005,Southampton England,Tom Watson,84.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DEC,red

In [6]:
ufc_table.describe()

,BPrev,BStreak,B_Age,B_Height,B_ID,B_Weight,B__Round1_Grappling_Reversals_Landed,B__Round1_Grappling_Standups_Landed,B__Round1_Grappling_Submissions_Attempts,B__Round1_Grappling_Takedowns_Attempts,...,R__Round5_TIP_Distance Time,R__Round5_TIP_Ground Control Time,R__Round5_TIP_Ground Time,R__Round5_TIP_Guard Control Time,R__Round5_TIP_Half Guard Control Time,R__Round5_TIP_Misc. Ground Control Time,R__Round5_TIP_Mount Control Time,R__Round5_TIP_Neutral Time,R__Round5_TIP_Side Control Time,R__Round5_TIP_Standing Time
count,2318.000000,2318.000000,2301.000000,2301.000000,2318.000000,2306.000000,1647.000000,1647.000000,1647.000000,1647.000000,...,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000
mean,2.391286,0.744607,31.776184,177.327249,2120.001726,73.699480,0.074681,1.103825,0.577413,3.852459,...,251.411111,33.644444,64.903704,6.855556,3.977778,4.303704,12.011111,262.740741,4.381481,303.103704
std,2.539978,1.145596,4.165267,8.807620,705.089725,15.425347,0.305691,1.537946,1.049758,5.261864,...,197.588561,75.756504,100.516057,25.786323,13.039241,12.810181,39.171198,199.940529,20.941919,224.848078
min,0.000000,0.000000,20.000000,152.000000,129.000000,52.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,29.000000,172.000000,1910.250000,61.000000,0.000000,0.000000,0.000000,0.000000,...,137.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,137.000000,0.000000,178.000000
50%,2.000000,0.000000,31.000000,177.000000,2230.000000,70.000000,0.000000,1.000000,0.000000,2.000000,...,222.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,258.500000,0.000000,296.500000
75%,4.000000,1.000000,35.000000,182.000000,2709.000000,84.000000,0.000000,2.000000,1.000000,5.000000,...,299.000000,34.000000,98.000000,0.000000,0.000000,0.000000,2.000000,300.000000,0.000000,364.000000
max,14.000000,10.000000,48.000000,213.000000,3196.000000,120.000000,3.000000,13.000000,8.000000,47.000000,...,1259.000000,633.000000,666.000000,144.000000,91.000000,62.000000,273.000000,1291.000000,200.000000,1473.000000

In [7]:
ufc_table.query("winner == 'blue'").shape[0]

951

In [8]:
ufc_table.query("winner == 'red'").shape[0]

1327

In [9]:
ufc_table.shape[1]

894